// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const shopPrice: string;
export const hasDiscount: string;
export const shopPriceOriginal: string;
