exclude: ["scripts", "Gemfile", "Gemfile.lock", "README.md"]
future: true

collections:
  schedule_days:
    output: true
    permalink: /schedule/:name
  schedule_skates:
    output: true
    permalink: /schedule/:name
  shop_tshirts:
    output: true
    permalink: /shop/:name

defaults:
  - 
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: schedule_days
    values:
      layout: schedule/schedule_day
  -
    scope:
      path: ""
      type: schedule_skates
    values:
      layout: schedule/schedule_skate
  -
    scope:
      path: ""
      type: shop_tshirts
    values:
      layout: shop/shop_tshirt