exclude: ["scripts", "Gemfile", "Gemfile.lock", "README.md"]
future: true

collections:
  schedule_days:
    output: true
    permalink: /schedule/:name
  schedule_skates:
    output: true
    permalink: /schedule/:name
  pages:
    output: true
    permalink: /:name

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "layout.html"
  -
    scope:
      path: ""
      type: "schedule_days"
    values:
      layout: "schedule/schedule_day.html"
  -
    scope:
      path: ""
      type: "schedule_skates"
    values:
      layout: "schedule/schedule_skate.html"