// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const logo: string;
export const logoImage: string;
export const date: string;
export const expiredDate: string;
export const menu: string;
