// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const shopProducts: string;
export const shopProductImageContainer: string;
export const shopProductImageContainer2: string;
export const shopProductImage: string;
